FROM n8nio/n8n

RUN apk update && apk add python3 py3-pip build-base python3-dev \
    libffi-dev libressl-dev gfortran openblas-dev
RUN apk add ffmpeg
RUN pip3 install --upgrade pip

COPY python/requirements.txt .

RUN pip3 install -r requirements.txt

RUN rm requirements.txt
