FROM n8nio/n8n

RUN echo "http://dl-8.alpinelinux.org/alpine/latest-stable/community" >> /etc/apk/repositories

RUN apk add --update \
   python3 \
   python3-dev \
   py3-pip \
   py3-numpy py3-pandas py3-scipy py3-numpy-dev

RUN apk add ffmpeg

RUN pip3 install --upgrade pip

COPY python/requirements.txt .

# Install pandas, numpy and other Python packages from the source
RUN apk add --no-cache --virtual .build-deps \
    g++ \
    make \
    && pip3 install -r requirements.txt \
    && apk del .build-deps \
    && rm requirements.txt

# Grant write permission to the python_dir directory for the node user
RUN mkdir -p /data/python_dir && chown -R node:node /data/python_dir
